### ISSUE TITLE
[auto-import] identifier toRef already defined with vue

### ISSUE THREAD

**Issue by OneTaro** [Mochenghualei/50projects-vue3#2]
Error: [auto-import] identifier toRef already defined with vue
    at file:///D:/workspace/opensource/vue/50projects-vue3/node_modules/unplugin-auto-import/dist/chunk-NNCQN3P6.js:243:17
    at Array.forEach (<anonymous>)
    at flattenImports (file:///D:/workspace/opensource/vue/50projects-vue3/node_modules/unplugin-auto-import/dist/chunk-NNCQN3P6.js:220:17)
    at createContext (file:///D:/workspace/opensource/vue/50projects-vue3/node_modules/unplugin-auto-import/dist/chunk-NNCQN3P6.js:102:19)
    at file:///D:/workspace/opensource/vue/50projects-vue3/node_modules/unplugin-auto-import/dist/chunk-NNCQN3P6.js:253:13
    at file:///D:/workspace/opensource/vue/50projects-vue3/node_modules/unplugin/dist/index.mjs:1199:32
    at file:///D:/workspace/opensource/vue/50projects-vue3/vite.config.js.timestamp-1732677158213.mjs:10:5
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadConfigFromBundledFile (file:///D:/workspace/opensource/vue/50projects-vue3/node_modules/vite/dist/node/chunks/dep-3e87c7b2.js:63148:21)

**Comment by julyL** [comment]
修改vite.config.js文件：  imports: ['vue', 'pinia', 'vue-router' /*'@vueuse/core'*/],   注释掉：@vueuse/core

**Comment by Hub-yang** [comment]
> 修改vite.config.js文件： imports: ['vue', 'pinia', 'vue-router' /_'@vueuse/core'_/], 注释掉：@vueuse/core

**Comment by Hub-yang** [comment]
https://github.com/Hub-yang/50projects-vue3/issues/2#issuecomment-2675979120
